#!/bin/bash

parent_dir="../"

for file in *.html; do
    if [ -f "$parent_dir$file" ]; then
        # Compare modification times
        if [ "$file" -nt "$parent_dir$file" ]; then
            echo "Copying $file to $parent_dir$file"
            cp "$file" "$parent_dir$file"
        else
            echo "$file already exists in $parent_dir and is newer."
        fi
    else
        echo "Copying $file to $parent_dir"
        cp "$file" "$parent_dir"
    fi
done
